name: Playwright Tests

on: 
  workflow_dispatch:
   inputs:
    test_tag:
      description: 'Test category'
      required: true
      type: choice
      options:
      - '@smoke'
      - '@regression'
jobs:
 tests:
  runs-on: ubuntu-latest
  
  steps:
   - name: checkout code
     uses: actions/checkout@v4

   - name: setup node.js
     uses: actions/setup-node@v4
     with:
      node-version: '18'
      cache: 'npm'

   - name: install dependencies
     run: npm ci

   - name: install browser
     run: npx playwright install --with-deps chromium

   - name: generate bdd tests from feature files
     run: npx bddgen
    
   - name: run tests
     run: npx playwright test --grep "${{github.event.inputs.test_tag }}" 
     env: 
        BASE_URL:       ${{ secrets.QA_BASE_URL}}
        API_URL:        ${{ secrets.QA_API_URL}}
        API_TOKEN:      ${{ secrets.QA_API_TOKEN}}
        LOGIN_EMAIL:    ${{ secrets.QA_LOGIN_EMAIL}}
        LOGIN_PASSWORD: ${{ secrets.QA_LOGIN_PASSWORD}}

   - name: upload artifacts
     if: always()
     uses: actions/upload-artifact@v4
     with:
      name: playwright-report
      path: playwright-report/
      retention-days: 7
      
   - name: upload debug screenshot
     if: always()
     uses: actions/upload-artifact@v4
     with:
      name: debug-screenshot
      path: debug-before-accept.png